name: Deploy Production

on:
  push:
    branches: ["v2"]
  workflow_dispatch:
    branches: ["v2"]

jobs:
  v2_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          ref: "v2"

      - name: Setup Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          go env -w CGO_ENABLED=0
          go build -v .

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            scilifen/saturday:latest
            scilifen/saturday:${{ steps.date.outputs.today }}

      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          connect_timeout: 10s
          script: |
            cd /home/nbtca/weekend/saturday_prod
            sudo docker-compose stop && docker-compose rm -f
            sudo docker rmi scilifen/saturday:latest
            sudo docker-compose up -d